# Settings for Bun (can be overriden by CLI arguments)
# https://bun.sh/docs/runtime/bunfig
telemetry = false

[run]
# execute "run" commands with "bun" instead of "node" (note: bun's default is "node"
bun = true

[install]
# set exact package versions in package.json
# for more precise dependency version management
exact = true

frozenLockfile = true
globalDir = "/home/app/.bun/install/global"
globalBinDir = "/home/app/.bun/bin"

[install.lockfile]
save = false

[install.cache]
dir = "/home/app/.bun/install/cache"
